module.exports.ERROR_CODE_INVALID_AUTHORIZATION = 50100;
module.exports.ERROR_CODE_MISSING_AUTHORIZATION = 50200;
module.exports.ERROR_CODE_MISSING_HEADER        = 50300;
module.exports.ERROR_CODE_INVALID_SIMULATION_ID = 50400;
