openapi: 3.0.0

info:
  version: 1.0.0
  title: Scenario Editor

servers:
  - url: 'http://localhost:3000'

# API Authentication (applies to all endpoints).
# <https://swagger.io/docs/specification/authentication/bearer-authentication/>
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

# Endpoints.
paths:
  /api/v1/dashboard:
    get:
      summary: 'Instructor dashboard summary'
      operationId: dashboard
      tags:
        - dashboard
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          content:
            application/json:
              schema:
                type: object
                required:
                  - drafts
                  - open
                  - closed
                properties:
                  drafts:
                    type: integer
                    items:
                      $ref: '#/components/schemas/Simulation'
                  open:
                    type: integer
                    items:
                      $ref: '#/components/schemas/Simulation'
                  closed:
                    type: integer
                    items:
                      $ref: '#/components/schemas/Simulation'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

# Object schemas.
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - explanation
      properties:
        explanation:
          type: string
