openapi: 3.0.0

info:
  version: 1.0.0
  title: Scenario Editor

servers:
  - url: 'http://localhost:3000'

components:
  # Object schemas.
  schemas:
    Simulation:
      type: integer
      format: int64
    Error:
      type: object
      required:
        - explanation
      properties:
        explanation:
          type: string
  # API Authentication (applies to all endpoints).
  # <https://swagger.io/docs/specification/authentication/bearer-authentication/>
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

# Endpoints.
paths:
  /api/v1/dashboard:
    get:
      summary: 'Instructor dashboard summary'
      operationId: dashboard
      tags:
        - dashboard
      responses:
        '200':
          description: "Sample response: Summary of an instructor's simulations"
          content:
            application/json:
              schema:
                type: object
                required:
                  - drafts
                  - open
                  - closed
                properties:
                  drafts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Simulation'
                  open:
                    type: array
                    items:
                      $ref: '#/components/schemas/Simulation'
                  closed:
                    type: array
                    items:
                      $ref: '#/components/schemas/Simulation'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/simulation/{simulation_id}:
    delete:
      summary: 'Remove a saved simulation'
      operationId: removeSimulation
      tags:
        - simulation
      responses:
        '200':
          description: 'Sample response: No associated response'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/simulation/{simulation_id}/start:
    post:
      summary: 'Start a saved simulation'
      operationId: startSimulation
      tags:
        - simulation
      requestBody:
        description: 'Student IDs to which this simulation will be available to'
        content:
          'application/json':
            schema:
              type: object
              required:
                - available_to
              properties:
                available_to:
                  type: array
                  items:
                    type: integer
      responses:
        '200':
          description: 'Sample response: No associated response'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/simulation/{simulation_id}/close:
    post:
      summary: 'Close a started simulation'
      operationId: closeSimulation
      tags:
        - simulation
      responses:
        '200':
          description: 'Sample response: No associated response'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
